node_js: lts/*
language: node_js

env:
  global: 
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"

jobs:
  include:
    - stage: test
      script:
      - |
        COVERAGE=1 npm run all -- --x64 --no-compress
        npx codecov
    - stage: "distro"
      name: "Build Linux distro"
      os: linux
      script:
      - npm run build -- --linux --publish
    - stage: "distro"
      name: "Build Windows distro"
      os: windows
      script:
      - |
        echo $WIN_CSC_LINK > cert.p12
        certutil -p $WIN_CSC_KEY_PASSWORD -importpfx ./cert.p12
        npm run build -- --win --publish --certificateFingerprint=$WIN_CSC_FINGERPRINT
    - stage: "distro"
      name: "Build MacOS distro"
      os: osx
      osx_image: xcode11.2
      script: 
      - npm run build -- --mac --publish
    - stage: "post distro"
      git:
        depth: false
      script:
      - npm run send-license-book-summary
    - stage: "nightly build"
      name: "Build Linux nightly"
      script:
      - |
        git checkout -b build-nightly
        npm run build -- --linux --nightly --publish
    - stage: "nightly build"
      name: "Build Windows nightly"
      os: windows
      script:
      - |
        git checkout -b build-nightly
        echo $WIN_CSC_LINK > cert.p12
        certutil -p $WIN_CSC_KEY_PASSWORD -importpfx ./cert.p12
        npm run build -- --win --nightly --publish --certificateFingerprint=$WIN_CSC_FINGERPRINT
    - stage: "nightly build"
      name: "Build MacOS nightly"
      os: osx
      osx_image: xcode11.2
      script:
      - |
        git checkout -b build-nightly
        npm run build -- --mac --nightly --publish

stages:
  - name: test
  - name: "distro"
    if: tag =~ ^v\d
  - name: "post distro"
    if: tag =~ ^v\d
  - name: "nightly build"
    if: type IN (cron)
